INSERT INTO RP_AGENTE(ID,NOMBRE,CODIGO) VALUES (1,'AGENTE UNO',101);
INSERT INTO RP_AGENTE(ID,NOMBRE,CODIGO) VALUES (2,'AGENTE DOS',102);
INSERT INTO RP_AGENTE(ID,NOMBRE,CODIGO) VALUES (3,'AGENTE TRES',103);
INSERT INTO RP_AGENTE(ID,NOMBRE,CODIGO) VALUES (4,'AGENTE CUATRO',104);
INSERT INTO RP_AGENTE(ID,NOMBRE,CODIGO) VALUES (5,'AGENTE CINCO',105);
INSERT INTO RP_AGENTE(ID,NOMBRE,CODIGO) VALUES (6,'AGENTE SEIS',106);